### ISSUE TITLE
Install error (md5 checksum)

### ISSUE THREAD

**Issue by markfarrall** [barretts/node-edgedriver#1]
Hi, just tried installing and I'm getting an md5 validation error that's (obviously) causing the install to error.

```
expect file md5:  e9c01360fbf15dd001811965e2a0ff68 to equal  9d52449623934aa12001fb682828f6dc
```

The relevant bits from the console and the npm.debug.log are attached if needed.
[console.txt](https://github.com/barretts/node-edgedriver/files/243694/console.txt)
[npm-debug.txt](https://github.com/barretts/node-edgedriver/files/243696/npm-debug.txt)

Let me know if there's anything else I can do to help.

**Comment by barretts** [comment]
The MD5 value was different again from when you had made this issue. I removed the MD5 check so this should be resolved!

**Comment by markfarrall** [comment]
Thanks!
