### ISSUE TITLE
make availble regardless

### ISSUE THREAD

**Issue by MichaelOdumosu57** [barretts/node-edgedriver#11]
can your software just allow me to install MircosoftWebDriver (im using ubuntu 16.04) I ask this because my selenium service is done through sauceLabs and it would be nice If I can convenivently bootstrap edge automation to sauceLabs directly from my ubuntu workstation

**Comment by MichaelOdumosu57** [comment]
anyone see my message

**Comment by barretts** [comment]
This isn't a project I'm actively supporting. Feel free to fork it for your needs.
